export const adminPage = String.raw`<!doctype html>
<html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>크누아 관리자</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f6fa;color:#253047;font:15px/1.6 system-ui,-apple-system,sans-serif}main{max-width:1040px;margin:auto;padding:40px 24px}header,.section-head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}header{margin-bottom:28px}h1,h2,h3,p{margin:0}h1{font-size:26px;letter-spacing:-1px}h2{font-size:20px}h3{font-size:17px}.eyebrow{color:#6f55cd;font-weight:700;font-size:12px;letter-spacing:1px}.sub{color:#768095;font-size:13px;margin-top:4px}button,input,textarea{font:inherit;border:1px solid #dce0e9;border-radius:10px;padding:10px 14px}button{cursor:pointer;background:white;color:#384259;font-weight:600}button:hover{background:#f1eefb}button:disabled{opacity:.5;cursor:wait}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #ad99ee;outline-offset:2px}.primary{background:#7156cf;color:white;border-color:#7156cf}.danger{color:#b63745;border-color:#efd5d8}.tools{display:flex;gap:8px;flex-wrap:wrap}.box,article{background:white;border:1px solid #e4e7ef;border-radius:16px;padding:22px}.box{margin-bottom:26px}#login{max-width:420px;margin:50px auto}label{display:block;margin:16px 0}input,textarea{width:100%;margin-top:6px;background:#fcfcfe}.section-head{margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}article{padding:20px;display:flex;flex-direction:column;gap:12px}article p{white-space:pre-wrap;overflow-wrap:anywhere;color:#626d82}.badge{display:inline-block;border-radius:6px;padding:2px 8px;font-size:12px;background:#eee9fb;color:#7156cf;margin-bottom:6px}.reason{padding:12px;background:#fff5ee;border-radius:9px;color:#966144!important}.actions{margin-top:auto;justify-content:flex-end;flex-wrap:wrap}.empty{padding:28px;text-align:center;color:#7b8494;background:#fafbfe;border-radius:12px;grid-column:1/-1}#message{margin-bottom:18px;color:#6a4cbb;min-height:24px}.search{display:flex;gap:8px;margin-bottom:18px}.search input{margin:0}textarea{resize:vertical}.more{display:block;margin:18px auto 0}small{color:#8992a3}[hidden]{display:none!important}@media(max-width:650px){main{padding:24px 16px}.grid{grid-template-columns:1fr}header{align-items:flex-start}.box{padding:16px}.section-head{align-items:flex-start;flex-direction:column}h1{font-size:23px}}
</style><main><header><div><div class="eyebrow">KNU AUDIO</div><h1>크누아 관리자</h1><p class="sub">고정 멘트와 교류 게시물을 관리하세요.</p></div><div id="toolbar" class="tools" hidden><button id="refresh">새로고침</button><button id="logout">로그아웃</button></div></header><p id="message" role="status" aria-live="polite"></p>
<form id="login" class="box"><h2>관리자 로그인</h2><p class="sub">관리자 계정으로만 접속할 수 있어요.</p><label>아이디<input name="username" autocomplete="username" required maxlength="80"></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required maxlength="256"></label><button class="primary">로그인</button></form>
<div id="panel" hidden><section class="box"><h2>고정 멘트</h2><p class="sub">저장한 문장은 다음 정기 음성 생성이 완료되면 반영돼요. 그때까지는 기존 음성이 재생됩니다.</p><form id="fixedForm"><label for="fixedText">마무리 인사 전에 들려줄 멘트</label><textarea id="fixedText" rows="4" maxlength="500" required disabled></textarea><p><small id="fixedCount">0 / 500자</small></p><button id="fixedSave" class="primary" disabled>멘트 저장</button><p id="fixedStatus" role="status" aria-live="polite"></p></form></section><section class="box"><div class="section-head"><div><h2>신고된 글</h2><p class="sub">최근 신고부터 표시해요. 같은 글의 여러 신고도 확인할 수 있어요.</p></div><span class="badge">우선 확인</span></div><div id="reports" class="grid"></div><button id="reportMore" class="more" hidden>신고 더 보기</button></section><section class="box"><div class="section-head"><div><h2>전체 게시물</h2><p class="sub">신고되지 않은 글과 숨긴 글도 관리할 수 있어요.</p></div></div><form id="search" class="search"><input name="query" aria-label="게시물 제목 검색" placeholder="제목으로 검색" maxlength="80"><button>검색</button></form><div id="posts" class="grid"></div><button id="postMore" class="more" hidden>게시물 더 보기</button></section></div></main>
<script nonce="__NONCE__">
const login=document.querySelector('#login'),panel=document.querySelector('#panel'),toolbar=document.querySelector('#toolbar'),message=document.querySelector('#message'),search=document.querySelector('#search');
const fixedForm=document.querySelector('#fixedForm'),fixedText=document.querySelector('#fixedText'),fixedSave=document.querySelector('#fixedSave'),fixedStatus=document.querySelector('#fixedStatus');let fixedVersion=null;
const lists={reports:{container:document.querySelector('#reports'),more:document.querySelector('#reportMore'),cursor:null},meetings:{container:document.querySelector('#posts'),more:document.querySelector('#postMore'),cursor:null}};let query='',searchVersion=0;const pending=new Set();
function say(e){message.textContent=e.message||e;}
function signedIn(ok){login.hidden=ok;panel.hidden=!ok;toolbar.hidden=!ok;if(!ok){fixedText.value='';fixedText.disabled=true;fixedSave.disabled=true;fixedVersion=null;fixedStatus.textContent='';for(const list of Object.values(lists))list.container.replaceChildren();login.elements.password.value='';}}
async function api(path,method='GET',body){const r=await fetch('/admin/api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok){if(r.status===401)signedIn(false);throw Error(d.error||'요청 실패');}return d;}
function node(tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;return el;}
function card(item,reported){const post=reported?item.post:item,el=document.createElement('article');el.dataset.id=post.id;const badge=node('span',post.hidden?'숨김':post.closed?'모집 마감':'공개','badge');el.append(badge,node('h3',post.title),node('p',post.intro||''));el.append(node('small',[post.when,post.where].filter(Boolean).join(' · ')));if(reported){el.append(node('p','신고 사유: '+item.reason,'reason'),node('small',new Date(item.reportedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})));}const actions=node('div','','actions'),hide=node('button',post.hidden?'숨김 해제':'글 숨기기'),del=node('button','삭제','danger');hide.dataset.action='hide';hide.dataset.hidden=String(post.hidden);
async function change(remove){if(pending.has(post.id))return;const hidden=hide.dataset.hidden!=='true';if(!confirm(remove?'이 글을 영구 삭제할까요? 신청 내역과 신고도 함께 삭제되며 되돌릴 수 없어요.':hidden?'이 글을 일반 이용자에게 숨길까요?':'이 글을 다시 공개할까요?'))return;pending.add(post.id);for(const c of document.querySelectorAll('article'))if(c.dataset.id===post.id)for(const b of c.querySelectorAll('button'))b.disabled=true;try{await api('meetings/'+post.id,remove?'DELETE':'PUT',remove?{confirmId:post.id}:{hidden});if(remove){await reload();say('게시물을 삭제했어요.');}else{for(const c of document.querySelectorAll('article'))if(c.dataset.id===post.id){c.querySelector('.badge').textContent=hidden?'숨김':post.closed?'모집 마감':'공개';const b=c.querySelector('[data-action=hide]');b.dataset.hidden=String(hidden);b.textContent=hidden?'숨김 해제':'글 숨기기';}say(hidden?'글을 숨겼어요.':'숨김을 해제했어요.');}}catch(e){say(e);}finally{pending.delete(post.id);for(const c of document.querySelectorAll('article'))if(c.dataset.id===post.id)for(const b of c.querySelectorAll('button'))b.disabled=false;}}
hide.onclick=()=>change(false);del.onclick=()=>change(true);actions.append(hide,del);el.append(actions);return el;}
async function load(kind,reset=true){const list=lists[kind],version=searchVersion;list.more.disabled=true;try{const params=new URLSearchParams();if(kind==='meetings'&&query)params.set('q',query);if(!reset&&list.cursor)params.set('cursor',list.cursor);const data=await api(kind+'?'+params);if(kind==='meetings'&&version!==searchVersion)return;if(panel.hidden)return;if(reset)list.container.replaceChildren();list.cursor=data.nextCursor;list.more.hidden=!list.cursor;for(const item of data.items)list.container.append(card(item,kind==='reports'));if(!list.container.children.length)list.container.append(node('p',kind==='reports'?'접수된 신고가 없어요.':'게시물이 없어요.','empty'));}finally{list.more.disabled=false;}}
async function loadFixed(){const data=await api('fixed-message');fixedText.value=data.text;fixedVersion=data.updatedAt;fixedText.disabled=false;fixedSave.disabled=false;countFixed();fixedStatus.textContent='';}
function countFixed(){document.querySelector('#fixedCount').textContent=fixedText.value.length+' / 500자';}
fixedText.oninput=countFixed;
fixedForm.onsubmit=async e=>{e.preventDefault();if(fixedSave.disabled)return;fixedSave.disabled=true;try{const data=await api('fixed-message','PUT',{text:fixedText.value,updatedAt:fixedVersion});fixedVersion=data.updatedAt;fixedText.value=data.text;countFixed();fixedStatus.textContent='저장했어요. 다음 정기 음성 생성 후 새 멘트를 들을 수 있어요.';}catch(e){fixedStatus.textContent=e.message;}finally{fixedSave.disabled=false;}};
async function reload(){await Promise.all([load('reports'),load('meetings'),loadFixed()]);}
login.onsubmit=async e=>{e.preventDefault();const b=login.querySelector('button');b.disabled=true;try{await api('login','POST',{username:login.elements.username.value,password:login.elements.password.value});signedIn(true);say('');await reload();}catch(e){say(e);}finally{login.elements.password.value='';b.disabled=false;}};
search.onsubmit=e=>{e.preventDefault();query=search.elements.query.value.trim();searchVersion++;load('meetings').catch(say);};
document.querySelector('#refresh').onclick=()=>reload().catch(say);document.querySelector('#logout').onclick=async()=>{try{await api('logout','POST');signedIn(false);say('로그아웃했어요.');}catch(e){say(e);}};
for(const [kind,list]of Object.entries(lists))list.more.onclick=()=>load(kind,false).catch(say);
api('session').then(()=>{signedIn(true);return reload();}).catch(e=>{if(e.message!=='관리자 로그인이 필요해요.')say(e);});
</script></html>`;
