export const adminPage = String.raw`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>크누아 관리자</title><style>body{font:16px system-ui;max-width:760px;margin:40px auto;padding:0 20px;background:#fafafa;color:#222}input,button{font:inherit;padding:10px;margin:5px}label{display:block}article{background:white;border:1px solid #ddd;border-radius:12px;padding:18px;margin:16px 0}p{white-space:pre-wrap;overflow-wrap:anywhere}button{cursor:pointer}#message{color:#a12626} [hidden]{display:none!important}</style><h1>크누아 관리자</h1><p id="message" role="status"></p><form id="login"><label>아이디 <input name="username" autocomplete="username" required maxlength="80"></label><label>비밀번호 <input name="password" type="password" autocomplete="current-password" required maxlength="256"></label><button>로그인</button></form><section id="panel" hidden><button id="refresh">새로고침</button><button id="logout">로그아웃</button><h2>접수된 신고</h2><div id="reports"></div><button id="more" hidden>더 보기</button></section><script nonce="__NONCE__">
const login=document.querySelector('#login'),panel=document.querySelector('#panel'),reports=document.querySelector('#reports'),message=document.querySelector('#message'),more=document.querySelector('#more');let cursor=null;
function signedIn(ok){login.hidden=ok;panel.hidden=!ok;if(!ok){reports.replaceChildren();login.password.value='';}}
async function api(path,method='GET',body){const r=await fetch('/admin/api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok){if(r.status===401)signedIn(false);throw Error(d.error||'요청 실패');}return d;}
function say(e){message.textContent=e.message||e;}
async function load(reset=true){if(reset)reports.replaceChildren();const d=await api('reports'+(!reset&&cursor?'?cursor='+encodeURIComponent(cursor):''));cursor=d.nextCursor;more.hidden=!cursor;for(const item of d.items){const card=document.createElement('article'),title=document.createElement('h3'),reason=document.createElement('p'),intro=document.createElement('p'),date=document.createElement('small'),button=document.createElement('button');title.textContent=item.post.title;intro.textContent=item.post.intro||'';reason.textContent='신고 사유: '+item.reason;date.textContent=new Date(item.reportedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});button.dataset.id=item.post.id;button.dataset.hidden=String(item.post.hidden);button.textContent=item.post.hidden?'숨김 해제':'글 숨기기';button.onclick=async()=>{const hidden=button.dataset.hidden!=='true';if(!confirm(hidden?'이 글을 일반 이용자에게 숨길까요?':'이 글을 다시 공개할까요?'))return;button.disabled=true;try{await api('meetings/'+item.post.id,'PUT',{hidden});for(const b of reports.querySelectorAll('button'))if(b.dataset.id===item.post.id){b.dataset.hidden=String(hidden);b.textContent=hidden?'숨김 해제':'글 숨기기';}say('변경했어요.');}catch(e){say(e);}finally{button.disabled=false;}};card.append(title,intro,reason,date,button);reports.append(card);}if(!reports.children.length)say('접수된 신고가 없어요.');}
login.onsubmit=async e=>{e.preventDefault();const button=login.querySelector('button');button.disabled=true;try{await api('login','POST',{username:login.username.value,password:login.password.value});signedIn(true);say('');await load();}catch(e){say(e);}finally{login.password.value='';button.disabled=false;}};
document.querySelector('#logout').onclick=async()=>{try{await api('logout','POST');signedIn(false);say('로그아웃했어요.');}catch(e){say(e);}};
document.querySelector('#refresh').onclick=()=>load().catch(say);more.onclick=async()=>{more.disabled=true;try{await load(false);}catch(e){say(e);}finally{more.disabled=false;}};
api('session').then(()=>{signedIn(true);return load();}).catch(say);
</script></html>`;
