import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {pbkdf2Sync} from 'node:crypto';
import worker from './worker.mjs';
const sqlite=new DatabaseSync(':memory:');
for(const file of ['0001_community.sql','0002_application_decisions.sql','0003_moderation.sql'])sqlite.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));
const db={prepare(sql){let args=[];const stmt=sqlite.prepare(sql);return{bind(...v){args=v;return this;},async first(){return stmt.get(...args)||null;},async all(){return{results:stmt.all(...args)};},async run(){return stmt.run(...args);}};}};
const salt='ab'.repeat(16),password='a strong test password',stored='pbkdf2-sha256:210000:'+salt+':'+pbkdf2Sync(password,Buffer.from(salt,'hex'),210000,32,'sha256').toString('hex');
const env={COMMUNITY_DB:db,ADMIN_USERNAME:'manager',ADMIN_PASSWORD_HASH:stored};
const owner='a'.repeat(64),other='b'.repeat(64);let cookie='';
async function call(path,method='GET',body,headers={}){const r=await worker.fetch(new Request('https://api.example'+path,{method,headers:{'Content-Type':'application/json',Origin:'https://api.example',Cookie:cookie,...headers},body:body===undefined?undefined:JSON.stringify(body)}),env);return{status:r.status,body:await r.json(),headers:r.headers};}
const admin='/admin/api/';
assert.equal((await call(admin+'reports')).status,401);
assert.equal((await call(admin+'login','POST',{username:'manager',password:'wrong'})).status,401);
assert.equal((await call(admin+'login','POST',{username:'manager',password},{Origin:'https://evil.example'})).status,403);
let r=await call(admin+'login','POST',{username:'manager',password});assert.equal(r.status,200);assert.deepEqual(r.body,{ok:true});cookie=r.headers.get('Set-Cookie').split(';')[0];assert.match(r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Strict/);
assert(!JSON.stringify(sqlite.prepare('SELECT * FROM community_admin_sessions').get()).includes(cookie.split('=')[1]));
const id=crypto.randomUUID(),post={id,category:'study',title:'테스트 모집',intro:'같이 공부',when:'화요일',where:'도서관',capacity:3,goal:'함께 공부',contact:''};
const meetings='/api/community/meetings';
assert.equal((await call(meetings,'POST',post,{Authorization:'Bearer '+owner})).status,201);
assert.equal((await call(meetings+'/'+id+'/reports','POST',{reason:'<img onerror=alert(1)>'},{Authorization:'Bearer '+other})).status,201);
assert.equal((await call(meetings+'/'+id+'/reports','POST',{reason:'다시 신고'},{Authorization:'Bearer '+other})).status,200);
assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM community_reports').get().n,1);
r=await call(admin+'reports');assert.equal(r.body.items[0].reason,'<img onerror=alert(1)>');assert(!JSON.stringify(r.body).includes('reporter_hash'));
assert.equal((await call(admin+'meetings/'+id,'PUT',{hidden:true},{Origin:'https://evil.example'})).status,403);
assert.equal((await call(admin+'meetings/'+id,'PUT',{hidden:true})).status,200);
assert.equal((await call(meetings)).body.items.length,0);
assert.equal((await call(meetings+'/'+id,'GET',undefined,{Authorization:'Bearer '+other})).status,404);
assert.equal((await call(meetings+'/'+id+'/applications','POST',{name:'참가자'},{Authorization:'Bearer '+other})).status,404);
assert.equal((await call(meetings+'/'+id,'PUT',{...post,closed:false,hidden:false},{Authorization:'Bearer '+owner})).body.item.hidden,true);
assert.equal((await call(admin+'meetings/'+id,'DELETE')).status,404);
assert.equal((await call(meetings+'/'+id+'/applications','DELETE',undefined,{Authorization:'Bearer '+other})).status,200);
for(let i=0;i<35;i++)sqlite.prepare('INSERT INTO community_reports VALUES(?,?,?,?)').run(id,'reporter'+i,'신고'+i,1700000000000);
r=await call(admin+'reports');assert.equal(r.body.items.length,30);assert(r.body.nextCursor);const next=await call(admin+'reports?cursor='+r.body.nextCursor);assert.equal(next.body.items.length,6);
assert.equal((await call(admin+'meetings/'+id,'PUT',{hidden:false})).status,200);assert.equal((await call(meetings)).body.items.length,1);
env.ADMIN_USERNAME='changed';assert.equal((await call(admin+'session')).status,401);env.ADMIN_USERNAME='manager';
sqlite.prepare('UPDATE community_admin_sessions SET expires_at=0').run();assert.equal((await call(admin+'session')).status,401);
r=await call(admin+'login','POST',{username:'manager',password});cookie=r.headers.get('Set-Cookie').split(';')[0];assert.equal((await call(admin+'logout','POST')).status,200);assert.equal((await call(admin+'session')).status,401);
for(let i=0;i<10;i++)await call(admin+'login','POST',{username:'manager',password:'wrong'},{'CF-Connecting-IP':'test-rate'});assert.equal((await call(admin+'login','POST',{username:'manager',password},{'CF-Connecting-IP':'test-rate'})).status,429);
const page=await worker.fetch(new Request('https://api.example/admin'),env);assert.match(page.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);const html=await page.text();assert(!html.includes('__NONCE__'));assert(!html.includes('innerHTML'));assert(!html.includes('localStorage'));
console.log('관리자 인증·CSRF·로그인 제한·세션 만료·신고 페이지 나누기·숨김·해제 통과');
